### ISSUE TITLE
Where can I find the module "comet2.comet_model"？

### ISSUE THREAD

**Issue by Tassadar007** [brcsomnath/commonsense-sarcasm#1]
Sorry to disturb you but I don't know where I can find and install this......

**Comment by brcsomnath** [comment]
You can install the package using the instructions provided in the repository: https://github.com/vered1986/comet-commonsense. I have added this in the README as well.

**Comment by Tassadar007** [comment]
> You can install the package using the instructions provided in the repository: https://github.com/vered1986/comet-commonsense. I have added this in the README as well.

Thank you very much!
